# Generated by Django 5.2.13 on 2026-04-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('duracion', models.DecimalField(decimal_places=2, help_text='Duración en minutos', max_digits=5)),
                ('genero', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Reggaeton', 'Reggaetón'), ('Jazz', 'Jazz'), ('Clasica', 'Clásica'), ('Electronica', 'Electrónica'), ('Hip Hop', 'Hip Hop')], max_length=50)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='gestion.artista')),
            ],
        ),
    ]
